# This is a config for E2B sandbox template.
# You can use template ID (r1flg0gsffbep0m848nf) or template name (lambda) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lambda") # Sync sandbox
# sandbox = await AsyncSandbox.create("lambda") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lambda')

team_id = "14e4a9e0-af9c-4241-a85b-38a895469e77"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lambda"
template_id = "r1flg0gsffbep0m848nf"
